// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tickets/PitcherTickets.tsx": () => import("../components/mockups/tickets/PitcherTickets.tsx"),
  "./components/mockups/tickets/ProviderTickets.tsx": () => import("../components/mockups/tickets/ProviderTickets.tsx")
};
